In [1]:
import pandas as pd
import numpy as np
import matplotlib as plt 
import seaborn as sns 

import keras
import tensorflow as tf #library
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import keras.models as km #framework
from keras.models import Sequential
from keras import activations, initializers, regularizers, constraints #regularizers - panelty and loss 
from keras.layers import Dense, Activation

In [2]:
df = pd.read_csv("./data/indian_liver_patient.csv")

In [3]:
df.head()

,Age,Gender,Total_Bilirubin,Direct_Bilirubin,Alkaline_Phosphotase,Alamine_Aminotransferase,Aspartate_Aminotransferase,Total_Protiens,Albumin,Albumin_and_Globulin_Ratio,Dataset
0,65,Female,0.7,0.1,187,16,18,6.8,3.3,0.90,1
1,62,Male,10.9,5.5,699,64,100,7.5,3.2,0.74,1
2,62,Male,7.3,4.1,490,60,68,7.0,3.3,0.89,1
3,58,Male,1.0,0.4,182,14,20,6.8,3.4,1.00,1
4,72,Male,3.9,2.0,195,27,59,7.3,2.4,0.40,1

In [4]:
df.describe()

,Age,Total_Bilirubin,Direct_Bilirubin,Alkaline_Phosphotase,Alamine_Aminotransferase,Aspartate_Aminotransferase,Total_Protiens,Albumin,Albumin_and_Globulin_Ratio,Dataset
count,583.000000,583.000000,583.000000,583.000000,583.000000,583.000000,583.000000,583.000000,579.000000,583.000000
mean,44.746141,3.298799,1.486106,290.576329,80.713551,109.910806,6.483190,3.141852,0.947064,1.286449
std,16.189833,6.209522,2.808498,242.937989,182.620356,288.918529,1.085451,0.795519,0.319592,0.452490
min,4.000000,0.400000,0.100000,63.000000,10.000000,10.000000,2.700000,0.900000,0.300000,1.000000
25%,33.000000,0.800000,0.200000,175.500000,23.000000,25.000000,5.800000,2.600000,0.700000,1.000000
50%,45.000000,1.000000,0.300000,208.000000,35.000000,42.000000,6.600000,3.100000,0.930000,1.000000
75%,58.000000,2.600000,1.300000,298.000000,60.500000,87.000000,7.200000,3.800000,1.100000,2.000000
max,90.000000,75.000000,19.700000,2110.000000,2000.000000,4929.000000,9.600000,5.500000,2.800000,2.000000

In [5]:
df.describe().round()

,Age,Total_Bilirubin,Direct_Bilirubin,Alkaline_Phosphotase,Alamine_Aminotransferase,Aspartate_Aminotransferase,Total_Protiens,Albumin,Albumin_and_Globulin_Ratio,Dataset
count,583.0,583.0,583.0,583.0,583.0,583.0,583.0,583.0,579.0,583.0
mean,45.0,3.0,1.0,291.0,81.0,110.0,6.0,3.0,1.0,1.0
std,16.0,6.0,3.0,243.0,183.0,289.0,1.0,1.0,0.0,0.0
min,4.0,0.0,0.0,63.0,10.0,10.0,3.0,1.0,0.0,1.0
25%,33.0,1.0,0.0,176.0,23.0,25.0,6.0,3.0,1.0,1.0
50%,45.0,1.0,0.0,208.0,35.0,42.0,7.0,3.0,1.0,1.0
75%,58.0,3.0,1.0,298.0,60.0,87.0,7.0,4.0,1.0,2.0
max,90.0,75.0,20.0,2110.0,2000.0,4929.0,10.0,6.0,3.0,2.0

In [6]:
df.isnull().sum()

Age                           0
Gender                        0
Total_Bilirubin               0
Direct_Bilirubin              0
Alkaline_Phosphotase          0
Alamine_Aminotransferase      0
Aspartate_Aminotransferase    0
Total_Protiens                0
Albumin                       0
Albumin_and_Globulin_Ratio    4
Dataset                       0
dtype: int64

In [7]:
df.shape

(583, 11)

In [8]:
df['Albumin_and_Globulin_Ratio'].unique()

array([0.9 , 0.74, 0.89, 1.  , 0.4 , 1.3 , 1.1 , 1.2 , 0.8 , 0.6 , 0.87,
       0.7 , 0.92, 0.55, 0.5 , 1.85, 0.95, 1.4 , 1.18, 0.61, 1.34, 1.39,
       1.6 , 1.58, 1.25, 0.78, 0.76, 1.55, 0.71, 0.62, 0.67, 0.75, 1.16,
       1.5 , 1.66, 0.96, 1.38, 0.52, 0.47, 0.93, 0.48, 0.58, 0.69, 1.27,
       1.12, 1.06, 0.53, 1.03, 0.68,  nan, 1.9 , 1.7 , 1.8 , 0.3 , 0.97,
       0.35, 1.51, 0.64, 0.45, 1.36, 0.88, 1.09, 1.11, 1.72, 2.8 , 0.46,
       0.39, 1.02, 2.5 , 0.37])

In [9]:
df['Albumin_and_Globulin_Ratio'] = df['Albumin_and_Globulin_Ratio'].fillna(df['Albumin_and_Globulin_Ratio'].mean())

In [10]:
df['Albumin_and_Globulin_Ratio'].dtype

dtype('float64')

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 583 entries, 0 to 582
Data columns (total 11 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Age                         583 non-null    int64
 1   Gender                      583 non-null    str
 2   Total_Bilirubin             583 non-null    float64
 3   Direct_Bilirubin            583 non-null    float64
 4   Alkaline_Phosphotase        583 non-null    int64
 5   Alamine_Aminotransferase    583 non-null    int64
 6   Aspartate_Aminotransferase  583 non-null    int64
 7   Total_Protiens              583 non-null    float64
 8   Albumin                     583 non-null    float64
 9   Albumin_and_Globulin_Ratio  583 non-null    float64
 10  Dataset                     583 non-null    int64
dtypes: float64(5), int64(5), str(1)
memory usage: 52.8 KB

In [12]:
df['Gender'].value_counts()

Gender
Male      441
Female    142
Name: count, dtype: int64

In [13]:
df['Gender'] = df['Gender'].replace({'Male':0,'Female':1})

In [14]:
df['Gender'].value_counts()
df['Gender'] = df['Gender'].astype('int64')

In [15]:
df['Dataset'].value_counts()

Dataset
1    416
2    167
Name: count, dtype: int64

In [16]:
df['Dataset'] = df['Dataset'].replace({2 : 0})
df['Dataset'].value_counts()

Dataset
1    416
0    167
Name: count, dtype: int64

In [17]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 583 entries, 0 to 582
Data columns (total 11 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Age                         583 non-null    int64
 1   Gender                      583 non-null    int64
 2   Total_Bilirubin             583 non-null    float64
 3   Direct_Bilirubin            583 non-null    float64
 4   Alkaline_Phosphotase        583 non-null    int64
 5   Alamine_Aminotransferase    583 non-null    int64
 6   Aspartate_Aminotransferase  583 non-null    int64
 7   Total_Protiens              583 non-null    float64
 8   Albumin                     583 non-null    float64
 9   Albumin_and_Globulin_Ratio  583 non-null    float64
 10  Dataset                     583 non-null    int64
dtypes: float64(5), int64(6)
memory usage: 50.2 KB

In [18]:
X = df.drop(columns=['Dataset'])
y = df['Dataset']
print(X.shape)
print(y.shape)

(583, 10)
(583,)

In [19]:
train_X,test_X,train_y,test_y = train_test_split(X,y,test_size=0.3,random_state=42)
print(train_X.shape)
print(train_y.shape)
print(test_X.shape)
print(test_y.shape)

(408, 10)
(408,)
(175, 10)
(175,)

In [20]:
model = Sequential()
model.add(Dense(units = 10, kernel_initializer = 'uniform', activation = 'relu', input_dim = 10))
model.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu')) #relu - rectify linear unit 
model.add(Dense(units = 4, kernel_initializer = 'uniform', activation = 'relu')) #units - 2^n
model.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'linear'))

C:\Users\Roshan\AppData\Local\Programs\Python\Python313\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [21]:
model.summary() # sequential : like a structure

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 10)                  │             110 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 6)                   │              66 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 4)                   │              28 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_3 (Dense)                      │ (None, 1)                   │               5 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 209 (836.00 B)

 Trainable params: 209 (836.00 B)

 Non-trainable params: 0 (0.00 B)

In [22]:
model.compile(loss='mean_squared_error', optimizer='adam')

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [23]:
model.fit(train_X, train_y, epochs=50, batch_size=32, validation_split=0.1)

# Evaluate the model
mse = model.evaluate(test_X, test_y)
print(f'Test Mean Squared Error: {mse}')

Epoch 1/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 3s 50ms/step - loss: 0.6993 - val_loss: 0.6625
Epoch 2/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.6744 - val_loss: 0.6332
Epoch 3/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.6320 - val_loss: 0.5781
Epoch 4/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.5429 - val_loss: 0.4663
Epoch 5/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.4070 - val_loss: 0.3043
Epoch 6/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.3089 - val_loss: 0.2346
Epoch 7/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.3048 - val_loss: 0.2223
Epoch 8/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.2897 - val_loss: 0.2293
Epoch 9/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.2812 - val_loss: 0.2322
Epoch 10/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.2734 - val_loss: 0.2177
Epoch 11/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.2668 - val_loss: 0.2209
Epoch 12/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.2622 - val_loss: 0.2120
Epoch 13/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.2585 - val_loss: 0.2091
Epoch 14/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.2519 - val_loss: 0.2027
Epoch 15/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.2492 - val_loss: 0.2037
Epoch 16/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.2441 - val_loss: 0.1999
Epoch 17/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.2407 - val_loss: 0.1967
Epoch 18/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.2372 - val_loss: 0.1993
Epoch 19/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.2337 - val_loss: 0.1957
Epoch 20/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.2301 - val_loss: 0.1935
Epoch 21/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.2268 - val_loss: 0.1906
Epoch 22/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.2238 - val_loss: 0.1890
Epoch 23/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.2211 - val_loss: 0.1872
Epoch 24/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.2186 - val_loss: 0.1848
Epoch 25/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.2165 - val_loss: 0.1875
Epoch 26/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.2136 - val_loss: 0.1835
Epoch 27/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.2120 - val_loss: 0.1820
Epoch 28/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.2103 - val_loss: 0.1823
Epoch 29/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.2072 - val_loss: 0.1800
Epoch 30/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.2053 - val_loss: 0.1794
Epoch 31/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.2034 - val_loss: 0.1800
Epoch 32/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.2024 - val_loss: 0.1793
Epoch 33/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.2017 - val_loss: 0.1798
Epoch 34/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.1996 - val_loss: 0.1780
Epoch 35/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.1992 - val_loss: 0.1781
Epoch 36/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.1980 - val_loss: 0.1786
Epoch 37/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.1976 - val_loss: 0.1784
Epoch 38/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.1966 - val_loss: 0.1784
Epoch 39/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.1962 - val_loss: 0.1778
Epoch 40/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.1961 - val_loss: 0.1784
Epoch 41/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.1955 - val_loss: 0.1788
Epoch 42/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.1950 - val_loss: 0.1786
Epoch 43/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.1951 - val_loss: 0.1782
Epoch 44/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.1950 - val_loss: 0.1789
Epoch 45/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.1944 - val_loss: 0.1785
Epoch 46/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.1945 - val_loss: 0.1786
Epoch 47/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.1945 - val_loss: 0.1792
Epoch 48/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.1939 - val_loss: 0.1788
Epoch 49/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.1955 - val_loss: 0.1789
Epoch 50/50
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.1937 - val_loss: 0.1795
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.1707
Test Mean Squared Error: 0.17069144546985626

In [24]:
predictions = model.predict(test_X)

6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step

In [25]:
import joblib

In [26]:
joblib.dump(model, "model.pkl")

print("Model saved successfully!")

Model saved successfully!

In [27]:
pip install streamlit

Requirement already satisfied: streamlit in C:\Users\Roshan\AppData\Local\Programs\Python\Python313\Lib\site-packages (1.63.0)
Requirement already satisfied: altair!=5.4.0,!=5.4.1,<7,>=5.0.0 in C:\Users\Roshan\AppData\Local\Programs\Python\Python313\Lib\site-packages (from streamlit) (6.2.2)
Requirement already satisfied: click<9,>=7.0 in C:\Users\Roshan\AppData\Local\Programs\Python\Python313\Lib\site-packages (from streamlit) (8.3.1)
Requirement already satisfied: numpy<3,>=1.23 in C:\Users\Roshan\AppData\Local\Programs\Python\Python313\Lib\site-packages (from streamlit) (2.4.1)
Requirement already satisfied: packaging>=20 in C:\Users\Roshan\AppData\Local\Programs\Python\Python313\Lib\site-packages (from streamlit) (26.0)
Requirement already satisfied: pandas<4,>=1.4.0 in C:\Users\Roshan\AppData\Local\Programs\Python\Python313\Lib\site-packages (from streamlit) (3.0.0)
Requirement already satisfied: pillow<13,>=7.1.0 in C:\Users\Roshan\AppData\Local\Programs\Python\Python313\Lib\site-packages (from streamlit) (12.1.0)
Requirement already satisfied: pydeck<1,>=0.8.0b4 in C:\Users\Roshan\AppData\Local\Programs\Python\Python313\Lib\site-packages (from streamlit) (0.9.3)
Requirement already satisfied: protobuf<8,>=5.26.1 in C:\Users\Roshan\AppData\Local\Programs\Python\Python313\Lib\site-packages (from streamlit) (7.36.1)
Requirement already satisfied: pyarrow!=25.0.0,<26,>=7.0 in C:\Users\Roshan\AppData\Local\Programs\Python\Python313\Lib\site-packages (from streamlit) (25.0.1)
Requirement already satisfied: requests<3,>=2.27 in C:\Users\Roshan\AppData\Local\Programs\Python\Python313\Lib\site-packages (from streamlit) (2.32.5)
Requirement already satisfied: toml<2,>=0.10.1 in C:\Users\Roshan\AppData\Local\Programs\Python\Python313\Lib\site-packages (from streamlit) (0.10.2)
Requirement already satisfied: typing-extensions<5,>=4.10.0 in C:\Users\Roshan\AppData\Local\Programs\Python\Python313\Lib\site-packages (from streamlit) (4.15.0)
Requirement already satisfied: starlette<2,>=0.46.0 in C:\Users\Roshan\AppData\Local\Programs\Python\Python313\Lib\site-packages (from streamlit) (1.6.0)
Requirement already satisfied: uvicorn<1,>=0.30.0 in C:\Users\Roshan\AppData\Local\Programs\Python\Python313\Lib\site-packages (from streamlit) (0.52.4)
Requirement already satisfied: httptools<1,>=0.6.3 in C:\Users\Roshan\AppData\Local\Programs\Python\Python313\Lib\site-packages (from streamlit) (0.8.0)
Requirement already satisfied: anyio<5,>=4.0.0 in C:\Users\Roshan\AppData\Local\Programs\Python\Python313\Lib\site-packages (from streamlit) (4.12.1)
Requirement already satisfied: python-multipart<1,>=0.0.10 in C:\Users\Roshan\AppData\Local\Programs\Python\Python313\Lib\site-packages (from streamlit) (0.0.32)
Requirement already satisfied: websockets<17,>=12.0.0 in C:\Users\Roshan\AppData\Local\Programs\Python\Python313\Lib\site-packages (from streamlit) (16.1.1)
Requirement already satisfied: itsdangerous<3,>=2.1.2 in C:\Users\Roshan\AppData\Local\Programs\Python\Python313\Lib\site-packages (from streamlit) (2.2.0)
Requirement already satisfied: watchdog<7,>=2.1.5 in C:\Users\Roshan\AppData\Local\Programs\Python\Python313\Lib\site-packages (from streamlit) (6.0.0)
Requirement already satisfied: jinja2 in C:\Users\Roshan\AppData\Local\Programs\Python\Python313\Lib\site-packages (from altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in C:\Users\Roshan\AppData\Local\Programs\Python\Python313\Lib\site-packages (from altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (4.26.0)
Requirement already satisfied: narwhals>=2.4.0 in C:\Users\Roshan\AppData\Local\Programs\Python\Python313\Lib\site-packages (from altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (2.26.0)
Requirement already satisfied: idna>=2.8 in C:\Users\Roshan\AppData\Local\Programs\Python\Python313\Lib\site-packages (from anyio<5,>=4.0.0->streamlit) (3.11)
Requirement already satisfied: colorama in C:\Users\Roshan\AppData\Local\Programs\Python\Python313\Lib\site-packages (from click<9,>=7.0->streamlit) (0.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\Roshan\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas<4,>=1.4.0->streamlit) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\Roshan\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas<4,>=1.4.0->streamlit) (2025.3)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\Roshan\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests<3,>=2.27->streamlit) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in C:\Users\Roshan\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests<3,>=2.27->streamlit) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in C:\Users\Roshan\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests<3,>=2.27->streamlit) (2026.1.4)
Requirement already satisfied: h11>=0.8 in C:\Users\Roshan\AppData\Local\Programs\Python\Python313\Lib\site-packages (from uvicorn<1,>=0.30.0->streamlit) (0.16.0)
Requirement already satisfied: MarkupSafe>=2.0 in C:\Users\Roshan\AppData\Local\Programs\Python\Python313\Lib\site-packages (from jinja2->altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (3.0.3)
Requirement already satisfied: attrs>=22.2.0 in C:\Users\Roshan\AppData\Local\Programs\Python\Python313\Lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in C:\Users\Roshan\AppData\Local\Programs\Python\Python313\Lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in C:\Users\Roshan\AppData\Local\Programs\Python\Python313\Lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in C:\Users\Roshan\AppData\Local\Programs\Python\Python313\Lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (0.30.0)
Requirement already satisfied: six>=1.5 in C:\Users\Roshan\AppData\Local\Programs\Python\Python313\Lib\site-packages (from python-dateutil>=2.8.2->pandas<4,>=1.4.0->streamlit) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

import streamlit as st
import joblib
import numpy as np

# Load model
model = joblib.load("model.pkl")

st.title("Machine Learning Prediction")

st.write("Enter the required values")

feature1 = st.number_input("Feature 1")
feature2 = st.number_input("Feature 2")
feature3 = st.number_input("Feature 3")
feature4 = st.number_input("Feature 4")

if st.button("Predict"):

    input_data = np.array([
        [feature1, feature2, feature3, feature4]
    ])

    prediction = model.predict(input_data)

    st.success(f"Prediction: {prediction[0]}")

In [28]:
 model.save("model.keras")

In [30]:
from tensorflow import keras

loaded_model = keras.models.load_model(
    "model.keras",
    compile=False
)

print("Model loaded successfully!")

Model loaded successfully!

In [32]:
prediction = loaded_model.predict(
    test_X[:1],
    verbose=0
)

print(prediction)

[[0.4888153]]